apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/fintech/arcadia-frontend:v5.2
          imagePullPolicy: IfNotPresent
          name: frontend
          env:
            - name: service_name
              value: frontend
            - name: protocol_use
              value: "http://"
            - name: site_name
              value: "arcadia-udf"
            - name: refer_friends_fqdn
              value: "refer-friends.arcadia.svc.cluster.local"
            - name: backend_fqdn
              value: "backend.arcadia.svc.cluster.local"
          name: frontend
          ports:
            - containerPort: 8080
            - containerPort: 8443
              protocol: TCP
      volumes:
        - name: default-conf
          configMap:
             name: sc-nginx-default-conf-9090-fe-cm
        - name: api-gw
          configMap:
             name: api-gw-fe.json
        - name: fe-to-money-backend-referfriends-postman
          configMap:
             name: fe-to-money-backend-referfriends-postman.json
        - name: run-apigen-fe
          configMap:
             name: run-apigen-fe.sh
             defaultMode: 0777
        - name: f5jsquery
          configMap:
             name: f5jsquery-cm
        - name: gptquery
          configMap:
             name: gptquery-cm
